// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lstmfefngokizyxqpbdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzdG1mZWZuZ29raXp5eHFwYmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjE5MDEsImV4cCI6MjA1OTUzNzkwMX0.6plt7vnykRNGri4_ymbMgvMCxX6LSHS7tCwkRkmzXtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);